### DISCUSSION TITLE
Evergreen not able to create dependabot.yml on a repo

### DISCUSSION THREAD

**Discussion by hkadakia** [github-community-projects/evergreen#209] [Q&A] [answered]
I am using version 1.12.0 for evergreen with the below config:

```
---
name: Weekly dependabot checks
on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * 0"

permissions:
  contents: read

jobs:
  evergreen:
    name: evergreen
    runs-on: {self-hosted-runner}
    permissions:
      issues: write

    steps:
      - name: Run evergreen action
        uses: github/evergreen@ff2f3ffd6bf88d33354f49a79ecbffd1d0cf98c9 #v1.12.0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORGANIZATION: <orgid>
          TITLE: "Add dependabot configuration"
          TYPE: pull
          BATCH_SIZE: 10
          ENABLE_SECURITY_UPDATES: true
          UPDATE_EXISTING: true
```
On one of the repos, I deleted an existing dependabot.yml file and then re-run this workflow. I expected this workflow to find the missing dependabot config file in the said repo & create a new pull request based on this config, but in the logs I only see the below message.

```
Checking my-repo/hello-go-container for compatible package managers
	No (new) compatible package manager found
```
Note: The repo above has dockerfile, github actions & go.mod & it had a dependabot with package managers for each of those.

Is there any additional settings I need to configure for the evergreen workflow to create a pull request if it detects a missing yml file?
